name: Test MagmaNode API

on:
  workflow_dispatch:

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install node-fetch
        
    - name: Run API Test
      run: node test-api.js
